lavanderia/prenda/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
url(r'^$', 'lavanderia.prenda.views.ver_tipo', name='r'),
url(r'^tipo$', 'lavanderia.prenda.views.registrar_tipo', name='r'),
#url(r'^buscar$', 'lavanderia.prenda.views.buscar', name='r'),
url(r'^ingresar/(\d+)/$', 'lavanderia.prenda.views.ingresar', name='r'),
url(r'^ingresar/$', 'lavanderia.prenda.views.ingresar', name='r'),
url(r'^borrar/([0-9])$', 'lavanderia.prenda.views.borrar_tipo', name='r'),
url(r'^resultado/(\d+)$', 'lavanderia.prenda.views.resultado', name='r'),
url(r'^ver/$', 'lavanderia.prenda.views.ver', name='r'),
url(r'^status/(\d+)$', 'lavanderia.prenda.views.status_update', name='r'),
url(r'^logout$', 'lavanderia.login.views.logout_auth', name='r'),
)

project/urls.py
from django.conf.urls import patterns, include, url
import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'lavanderia.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^prendas/', include('lavanderia.prenda.urls')),
    url(r'^clientes/', include('lavanderia.clientes.urls')),
    url(r'^prenda/', include('lavanderia.prenda.urls')),
    url(r'^login/', include('lavanderia.login.urls')),
    url(r'^logout$', 'lavanderia.login.views.logout_auth', name='r'),

    )
#+ static(settings.STATIC_URL, document_root="settings.STATIC_ROOT")
if settings.DEBUG:
  urlpatterns += patterns('',
  (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),)

lavanderia/prenda/models.py
# -*- coding: utf-8 -*-
from django.db import models
from lavanderia.clientes.models import Client

class TypeGarment(models.Model):
    name = models.CharField(max_length=40, verbose_name=u'Nombre')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name=u'Precio por Kilo')

    def __unicode__(self):
        return self.name


class Garment(models.Model):
    CHOICES_COLOR = (('azul', 'azul'),
                    ('rojo', 'rojo'),
                    ('amarillo', 'amarillo'),
                    ('verde', 'verde'),
                    ('blanco', 'blanco'),
                    ('negro', 'negro'))
    CHOICES_STATUS = (('R', 'Recibido'),
                    ('L', 'Lavado'),
                    ('S', 'Secado'),
                    ('P', 'Planchado'),
                    ('A', 'Almacenado'),
                    ('E', 'Entregado'))
    description = models.CharField(max_length=30, verbose_name=u'Descripción')
    type = models.ForeignKey(TypeGarment, verbose_name=u'Tipo')
    weight = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='peso')
    color = models.CharField(choices=CHOICES_COLOR, max_length=20)
    check_in = models.DateField(auto_now_add=True, verbose_name=u'ingreso')
    check_out = models.DateField(verbose_name=u'Fecha de entrega')
    status = models.CharField(max_length=1, choices=CHOICES_STATUS, default=CHOICES_STATUS[0][0])
    location = models.CharField(max_length=30, verbose_name=u'Ubicación', null=True, blank=True)
    client = models.ForeignKey(Client)

    def __unicode__(self):
        return self.description

    def get_status(self):
        status = dict(self.CHOICES_STATUS)
        return status[self.status]

    def price(self):
        return self.type.price * self.weight

'''class Ticket(models.Model):
    client = models.ForeignKey(Client)
    product = models.ManyToManyField(Product)

    def __unicode__(self):
        return  str(self.id)
'''

lavanderia/prenda/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm

from lavanderia.prenda.models import TypeGarment, Garment


class TypeGarmentForm(ModelForm):
    class Meta:
        model = TypeGarment
                #exclude = ('user', 'mission')


class GarmentForm(ModelForm):
    class Meta:
        model = Garment
        exclude = ('client', 'status')


class UpdateStatusForm(ModelForm):
    class Meta:
        model = Garment
        exclude = ('description', 'type', 'weight', 'color', 'check_in', 'check_out','client')

lavanderia/prenda/views.py
from django.shortcuts import render, render_to_response, redirect
from lavanderia.prenda.forms import TypeGarmentForm, GarmentForm, UpdateStatusForm
from django.template import RequestContext
from lavanderia.prenda.models import TypeGarment, Garment
from lavanderia.clientes.models import Client
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login')
def ver_tipo(request):
    tipos = TypeGarment.objects.all()
    data = {'tipos': tipos}
    return render_to_response('index_prenda.html', data,
                              context_instance=RequestContext(request))

@login_required(login_url='/login')
def borrar_tipo(request,tipo):
    tipo = TypeGarment.objects.get(id=tipo)
    tipo.delete()
    return redirect("/prendas")

@login_required(login_url='/login')
def registrar_tipo(request):
    if request.method == 'POST':
        form = TypeGarmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/prendas")
    else:
        form = TypeGarmentForm()
    data = {'form': form}
    print form.errors
    return render_to_response('registro_prenda.html', data,
                              context_instance=RequestContext(request))


@login_required(login_url='/login')
def ingresar(request, dni=None):
    if request.method == 'POST':
        form = GarmentForm(request.POST)
        if form.is_valid():
            id = request.POST.get('client',)
            client = Client.objects.get(id=id)
            form = form.save(commit=False)
            form.client = client
            form.save()
            if request.POST.get('final',):
                return redirect("/prendas/resultado/%s" % form.id)
            else:
                return redirect("/prenda/ingresar/%s" % dni)
        data = {'form': form}
    else:
        if dni is None:
            return redirect("/prendas/nueva")
        form = GarmentForm()
        client = Client.objects.get(dni=dni)
        data = {"form": form, "client": client}
    #data = {'form': form}
    print form.errors
    return render_to_response('ingreso_prenda.html', data,
                              context_instance=RequestContext(request))

@login_required(login_url='/login')
def ver(request):
    garment = Garment.objects.all()
    data = {'garments': garment}
    return render_to_response('prendas_ver.html', data,
                              context_instance=RequestContext(request))

@login_required(login_url='/login')
def status_update(request, id):
    garment = Garment.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateStatusForm(request.POST)
        if form.is_valid():
            status = request.POST.get('status', )
            location = request.POST.get('location')
            garment.status = status
            garment.location = location
            garment.save()
            return redirect("/prendas/ver")
    else:
        form = UpdateStatusForm()
    data = {'form': form, 'garment': garment}
    return render_to_response('status_update.html', data,
                                  context_instance=RequestContext(request))


@login_required(login_url='/login')
def resultado(request, id=None):
    garment = Garment.objects.get(id=id)

    data = {'garment': garment}
    return render_to_response('resultado_prenda.html', data,
                              context_instance=RequestContext(request))

lavanderia/prenda/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistema lavandería | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>

    <nav role="navigation" class="navbar navbar-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Lavanderia</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/clientes">Clientes</a></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Prendas <b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="/prendas">Tipos</a></li>
                        <li><a href="/clientes">Ingresar Nueva</a></li>
                        <li><a href="/prendas/ver">Listar</a></li>

                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="/logout">Cerrar Sesión</a></li>
                {% else %}
                <li><a href="/login">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
	<div class="jumbotron">
				   {% block canvas %}{% endblock canvas %}
			</div>
		</div>
	</div>
</div>
</body>
</html>

lavanderia/prenda/templates/index.html
{% extends 'base.html' %}
{% block title %}Registrar Usuarios{% endblock %}
{% block canvas %}
   <h1>Bienvenido</h1>

{% endblock canvas %}

lavanderia/prenda/templates/index_prenda.html
{% extends 'base.html' %}
{% block title %}Registrar Usuarios{% endblock %}
{% block canvas %}
    <h1>Tipos de prendas</h1>

<form id="formulario" action="/prendas/tipo" method="post">
    <fieldset>
      <label>Buscar</label>
      <input id="buscar" name="tipo" type="text" />
      {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
    </fieldset>
</form>
<div class="table-responsive">
  <table class="table table-condensed">
    <tr>
      <td><strong>Tipo</strong></td>
      <td><strong>Codigo</strong></td>
      <td><strong>Precio x Kilo</strong></td>
      <td></td>
  </tr>

    {% for tipo in tipos%}
    <tr>
        <td>{{tipo.id}}</td>
        <td>{{tipo.name}}</td>
        <td>{{tipo.price}}</td>
        <td><a href="/tipos/{{tipo.id}}">Editar</a></td>
        <td><a href="/tipos/borrar/{{tipo.id}}">Borrar</a></td>

    </tr>
    {% endfor%}

  </table>
</div>



{% endblock canvas %}

lavanderia/prenda/templates/ingreso_prenda.html
{% extends 'base.html' %}
{% block title %}Registrar prenda{% endblock %}
{% block canvas %}
    <h1>Ingresar Prenda</h1>
    <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
        <p>
            <label for="id_client">Cliente:</label>
            {{ client }}
            <input id="id_client" type="hidden" name="client" value="{{ client.id }}"></input>
        </p>

        <button type="submit" name="final" value="final" class="btn btn-success">Guardar y Finalizar</button>
        <button type="submit" value="seguir" class="btn btn-primary">Guardar y Seguir Agregando</button>

    </form>


{% endblock canvas %}

lavanderia/prenda/templates/login_auth.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block canvas %}
    <div class="container">
        <form class="form-signin" role="form" method="post" action="">
            {% csrf_token %}
            <h2 class="form-signin-heading">Ingrese sus datos</h2>
            <input type="text" name="username" class="form-control" placeholder="Usuario" required autofocus>
            <input type="password" name="password" class="form-control" placeholder="Password" required>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
        </form>

    </div>


{% endblock canvas %}

lavanderia/prenda/templates/prendas_ver.html
{% extends 'base.html' %}
{% block title %}Registrar Usuarios{% endblock %}
{% block canvas %}
    <h1>Prendas Registradas</h1>

<form id="formulario" action="/prendas/tipo" method="post">
    <fieldset>
      <label>Buscar</label>
      <input id="buscar" name="tipo" type="text" />
      {% csrf_token %}
      <input id="campo3" name="enviar" type="submit" value="buscar" />
    </fieldset>
</form>
<div class="table-responsive">
  <table class="table table-condensed">
    <tr>
      <td><strong>codigo</strong></td>
      <td><strong>descripción</strong></td>
      <td><strong>status</strong></td>
      <td><strong>ingreso</strong></td>
      <td><strong>recojo</strong></td>
      <td><strong>cliente</strong></td>
      <td></td>
  </tr>

    {% for garment in garments %}
    <tr>
        <td>{{garment.id}}</td>
        <td>{{garment.description}}</td>
        <td>{{garment.get_status}}</td>
        <td>{{garment.check_in}}</td>
        <td>{{garment.check_out}}</td>
        <td><a href="/clientes/ver/{{ garment.client.id }}">{{garment.client}}</a></td>
        <td><a href="/prendas/status/{{garment.id}}">Status</a></td>
        <td><a href="/prendas/resultado/{{garment.id}}">Ver más...</a></td>


    </tr>
    {% endfor%}

  </table>
</div>



{% endblock canvas %}

lavanderia/prenda/templates/registro_prenda.html
{% extends 'base.html' %}
{% block title %}Registrar Prenda{% endblock %}
{% block canvas %}
    <h1>Registrar tipo de prenda</h1>
    <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>


{% endblock canvas %}

lavanderia/prenda/templates/resultado_prenda.html
{% extends 'base.html' %}
{% block title %}Registrar Usuarios{% endblock %}
{% block canvas %}
    <h1>Ingreso</h1>

    <br>numero de ticket: {{garment.id}}</br>
    <br>Cliente:{{garment.client}}</br>
    <br>Prenda: {{garment.description}}</br>
    <br>Precio final: S./ {{garment.price}} nuevos soles</br>
    <br>fecha de ingreso: {{garment.check_in}}</br>
    <br>fecha de entrega: {{garment.check_out}}</br>
    <br>estado: {{garment.get_status}}</br>







{% endblock canvas %}

lavanderia/prenda/templates/status_update.html
{% extends 'base.html' %}
{% block title %}Actualizar Status{% endblock %}
{% block canvas %}
    <h1>Actualizar Status</h1>
    <h2> ticket: {{ garment.id }}</h2>
   <h2> descripción: {{ garment.description }}</h2>
    <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit"  class="btn btn-success">Guardar</button>

    </form>


{% endblock canvas %}